
export { _type } from './_type'
export { compose2 } from './compose2'
export { compose3 } from './compose3'
export { def } from './def'
export { defaultEnv } from './defaultEnv'
export { filter } from './filter'
export { hasMethod } from './hasMethod'
export { inspect } from './inspect'
export { method } from './method'
export { negativeZero } from './negativeZero'
export { prop } from './prop'
export { sentinel } from './sentinel'
export { a, b, c, d, f, l, r } from './typeVariables'
