#!/usr/bin/env bash
set -euf -o pipefail

node_modules/.bin/sanctuary-lint "$@"

function rewrite {
  local state=
  local line
  while IFS='' read -r line ; do
    local a="${line:0:1}"
    local b="${line:1:1}"
    local z="${line: -1}"
    if [[ $a$b == '> ' ]] ; then
      printf '\n%s' "${line:2}"
      state=input
    elif [[ -n $state && $a$b == '. ' ]] ; then
      printf '\n%s' "${line:2}"
    elif [[ $state == input && $a$z == '{}' ]] ; then
      printf ';\n%s' "($line)"
      state=output
    elif [[ $state == input ]] ; then
      printf ';\n%s' "$line"
      state=output
    elif [[ $state == output ]] ; then
      printf ';\n%s' "$line"
      state=
    else
      printf '\n%s' "$line"
    fi
  done
}

trap 'mv README.md.orig README.md && rm -f README.md.temp' EXIT
cp README.md README.md.orig
VERSION=0.0.0 PREVIOUS_VERSION=0.0.0 node_modules/.bin/sanctuary-generate-readme
cp README.md README.md.temp
rewrite <README.md.temp >README.md

node_modules/.bin/eslint --config eslint/es6.js -- README.md eslint
