#!/usr/bin/env node

'use strict';

var fs = require('fs');

var pkg = require('../package.json');

//  deps :: StrMap String
var deps = Object.assign({}, pkg.dependencies, pkg.devDependencies);

process.stdout.write(fs.readFileSync(process.argv[2], 'utf8').replace(
  new RegExp(' v:(.+)/(.+)#(.+)', 'g'),
  function(_, owner, name, id) {
    if (name in deps && /^\d+[.]\d+[.]\d+$/.test(deps[name])) {
      return ' https://github.com/' + owner + '/' + name +
             '/tree/v' + deps[name] + '#' + id;
    }
    process.stderr.write('Exact version not specified for ' + name + '\n');
    process.exit(1);
  }
));
